language: node_js
node_js:
  - '15'
# Cache node_modules
cache:
  directories:
    - 'node_modules'
install:
  - npm install
script:
  # do a full build
  - npm run build
  # run tests
  - npm run test
